### ISSUE TITLE
As a manager, I want a cost monitoring capability for AWS deployments

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/cloud-strategy#1]
...so that we can consistently monitor in some manner what our cost is, and tweak and fine tune our cost models over time.

**Acceptance Criteria**
TBD

**Notes**
This story could be broken down into an intermediate solution (e.g. email) vs. an enterprise-wide strategy for cost monitoring.

**Comment by jordanpadams** [comment]
Done per https://github.com/nasa-pds/pds-registry-app/issues/90

**Comment by gxtchen** [comment]
@jordanpadams @viviant100 How can I test this?

**Comment by jordanpadams** [comment]
@gxtchen let's ignore this for now. this would be done by inspection in the AWS console, but I don't think this is I&T-worthy. this is more manager-has-to-check-this-or-our-budget-could-explode worthy. 😄
